### ISSUE TITLE
Instructions to add on to an existing asterisk pbxinaflash hylafax system

### ISSUE THREAD

**Issue by chris001** [gonicus/gofaxip#10]
Congrats on your project, this seems like a great improvement over using spandsp analog modem emulator and going digital replacing hylafax's binaries with ones that go direct.
Could this be added on to an existing asterisk / freepbx / pbxinaflash / hylafax system.  This seems possible since ultimately it's an add-on to hylafax which then talks to freeswitch to accomplish the fax send/receive.
Just asking if you have insight into doing this in the interest of providing maximum possible fax send/receive speed and quality.

**Comment by markuslindenberg** [comment]
Should be possible if you run FreeSWITCH on a different port range as 5060 is in use by Asterisk. The FreeSWITCH process and config is very lightweight, so it might be feasible to just bind FreeSWITCH's SIP/RTP interface to loopback (e.g. Port 5090 or something else) and create a SIP peer in Asterisk that will get faxes forwarded. 

You might have to enable t.38 in Asterisk to send t.38 end to end and enable t.38 re-INVITEs.
