### ISSUE TITLE
Avantfax and gofaxip

### ISSUE THREAD

**Issue by aalejandro** [gonicus/gofaxip#11]
Not really a problem, just wanted to comment that a pretty much avantfax stock install on debian works wonderfully with gofaxip for OUTBOUND faxing. I was able to send almost 400 faxes today during our tests. 

Heres my /var/spool/hylafax/etc/config

```
LogFacility:            daemon
CountryCode:            1
AreaCode:               787
LongDistancePrefix:     1
InternationalPrefix:    011
DialStringRules:        etc/dialrules
ServerTracing:          1

MaxBatchJobs: 0
MaxConcurrentCalls: 5

# GOFAX

SendFaxCmd:     "/usr/local/sbin/gofaxsend"

#
## AvantFAX
#
NotifyCmd:      bin/notify.php
```

Inbound faxing is another story however, later on I will tackle that.

Thanks a lot!

**Comment by markuslindenberg** [comment]
Thanks for the feedback! I've never used Avantfax so it's great to hear that this works out of the box. :)
