### ISSUE TITLE
TIFF file cannot be opened.

### ISSUE THREAD

**Issue by whitebook** [gonicus/gofaxip#12]
/usr/local/sbin/gofaxd[1641]: sessionlog.go:69: Success: false, Hangup Cause: NORMAL_CLEARING, Result: TIFF/F file cannot be opened

/usr/local/sbin/gofaxd[1641]: sessionlog.go:69: Calling bin/faxrcvd [bin/faxrcvd recvq/fax00000007.tif freeswitch 00000007 TIFF/F file cannot be opened anonymous Anonymous 0000000000]

/usr/local/sbin/gofaxd[1641]: sessionlog.go:69: bin/faxrcvd ended successfully

Not sure what I should I be checking wonder if its a simple permissions issue.

I am running freeswitch as freeswitch user and hylafax as uucp.

**Comment by whitebook** [comment]
Yep -  File Permissions.

**Comment by derekhansell** [comment]
How did you fix this issue? I'm having the same problem on FreePBX.

**Comment by denzs** [comment]
As FreePBX is not using gofaxip the solution propably does not apply to your setup 1:1 ...
But for trying to help you need to post some more details...

* error message
* current file permissions of file contained in the message
* user of hylafax and other relevant processes

**Comment by symptog** [comment]
I'm running freeswitch as user freeswitch and gofaxd as uucp. I've got the same problem.
`chown -R freeswitch:uucp /var/spool/hylafax/recvq` fixed it for me.

```
drwxr-xr-x  17 uucp       uucp  4096 13. Jan 12:11 .
drwxr-xr-x. 16 root       root   197 17. Sep 2018  ..
...
drwxrwxr-x   2 freeswitch uucp    64 20. Apr 13:44 recvq
```

**Comment by denzs** [comment]
As documented in the readme.. freeswitch should be running as user uucp to avoid these kind of problems...
