### ISSUE TITLE
can't find file /dev/freeswitch

### ISSUE THREAD

**Issue by jonny1213** [gonicus/gofaxip#13]
Hi,
I have installed gofaxip on debian jessie on one system. There it work's with no problems.
On a second system I can receive fax but I'm unable to send a fax. I always get  "file /dev/freeswitchx" not found. Is there a problem with the gofaxsend ?

Thx
Regards Thomas

**Comment by markuslindenberg** [comment]
Hi Thomas, 

sounds like you forgot to set `SendFaxCmd` in `etc/config`:

```
SendFaxCmd:             "/usr/local/sbin/gofaxsend"
```

**Comment by jonny1213** [comment]
Hi Markus,
the probelm was, I put the SendFaxCmd in /var/spool/hylafax/etc/config not in /etc/hylafax/config.
Now I changed it and it works fine now.
Thanky you very much.
Thomas
