### ISSUE TITLE
DynamicConfig

### ISSUE THREAD

**Issue by jonny1213** [gonicus/gofaxip#14]
Hi,
I'm not sure how to use the DynamicConfig.
Do you have an example?
Thx
Thomas

**Comment by markuslindenberg** [comment]
Hi Thomas, 

for incoming faxes the functionality is documented in HylaFAX: http://www.hylafax.org/content/Handbook:Advanced_Server_Configuration:Per-call_Dynamic_Configuration

The supported options in GOfax.IP are documented here: https://github.com/gonicus/gofaxip#dynamicconfig-for-incoming-faxes

Please see #15 for an example for DynamicConfig for outgoing faxes.
