### ISSUE TITLE
DynamicConfigOutgoing

### ISSUE THREAD

**Issue by pquan** [gonicus/gofaxip#15]
It is not clear how to use DynamicConfigOutgoing and how to connect to the users in hylafax.

A little howto or just simple examples could be very nice

Thank you.

**Comment by markuslindenberg** [comment]
The feature can be used to reject outbound faxes and set metadata (TSI, Callerid, Tag line) based on the sending users's name and the destination number. 

A DynamicConfig script for outbound faxes can be configured in `/etc/gofax.conf` in the `[gofaxsend]` section:

```
[gofaxsend]
faxnumber = 1234567890
dynamicconfig = etc/DynamicConfigOutgoing
```

This will trigger the (executable) script `/var/spool/hylafax/etc/DynamicConfigOutgoing`. The script will have three arguments: `$1` is the modem name (irrelevant and just there for logging/compatibility purposes), `$2` is the fax owner's name and `$3` is the destination number.

One simple script I actually use in production:

```
#!/bin/bash

#echo "RejectCall: false"
#echo "LocalIdentifier: +49 1234 123456789"
#echo "TagLine: ACME Markus Lindenberg"
#echo "FAXNumber: 789"

faxnum=$(/usr/local/bin/uid2faxnum.py $2)

if [[ -n $faxnum ]]; then
	echo "FAXNumber: 123456$faxnum"
fi
```

The commented out `echo` statements show all currently supported options. In this case, the `DynamicConfigOutgoing` script will trigger a Python script that will look up the fax number (i.e. from a LDAP directory) for the sending user's name. If a number is found, the script will echo the `FAXNumber: ...` field to set the SIP caller ID FreeSWITCH should use in the INVITE.

Does this clarifiy usage for you?
