### ISSUE TITLE
Unable to open scheduler FIFO: No such device or address.

### ISSUE THREAD

**Issue by vasyugan** [gonicus/gofaxip#19]
Not sure whether hylafax or gofax.ip is at fault, but now every sendfax command fails:
460 Failed to submit job 8: Unable to open scheduler FIFO: No such device or address.
I see the following in syslog trying to start gofax.ip:

Mai 31 15:05:41 musicbox /usr/local/sbin/gofaxd[2611]: main.go:70: GOfax.IP gofaxd development version starting
Mai 31 15:05:41 musicbox /usr/local/sbin/gofaxd[2611]: device.go:173: Changing state of modem freeswitch0 to READY
Mai 31 15:05:41 musicbox /usr/local/sbin/gofaxd[2611]: faxq.go:72: Sending message to /var/spool/hylafax/FIFO: +freeswitch0:N
Mai 31 15:06:29 musicbox HylaFAX[2645]: `-> Got a: 127.0.0.1[13]
Mai 31 15:06:29 musicbox HylaFAX[2645]: `-> Got a: 53805[19]
Mai 31 15:06:29 musicbox HylaFAX[2645]: Filesystem has SysV-style file creation semantics.
Mai 31 15:06:29 musicbox HylaFAX[2645]: `-> Got a: 127.0.0.1[13]
Mai 31 15:06:29 musicbox HylaFAX[2645]: `-> Got a: 43231[19]

Also, while freeswitch is registered as a sip client, according to the sip provider, gofax never seems to pick up any call, whether phone or fax. It just remains silent and I see no notifications in the system journal.

**Comment by markuslindenberg** [comment]
That seems strange, never had that problem before. Is FreeSWITCH running as user uucp? Is hfaxd running? Is gofaxd running as user uucp?
