### ISSUE TITLE
Dynamic Send

### ISSUE THREAD

**Issue by alexcrow** [gonicus/gofaxip#22]
I'm looking to rewrite the CSID of outbound faxes dependent on the email address supplied to the hylafax client.

In Hylafax/T38Modem/FS I've been using a JobControl script like this:

> # !/bin/bash
> 
> JOBID=$1
> 
> GetJobParam ()
> {
>         grep "^$1:" sendq/q$JOBID | cut -d : -f 2-
> }
> 
> SetControlParam ()
> {
>     echo "$1: \"$2\""
> }
> 
> OWNER=$(GetJobParam owner)
> EMAIL=$(GetJobParam mailaddr)
> 
> if EMAIL="foo@bar.co.uk"
> then
> 
> ```
>     SetControlParam LocalIdentifier "020 7666 6601"
> ```
> 
> else
>         SetControlParam LocalIdentifier "020 7666 6600"
> fi

Am I correct in assuming that this will not work if I use it with gofaxip - and that the CSID will be overwritten with the static value in gofax.conf?

If so, I've had a look at the DynamicConfig stuff in gofax, eg:

Parameters The following arguments are provided to the DynamicConfig script for outgoing faxes:

```
Used modem name
Owner (User ID as set sendfax -o or the FAXUSER environment variable, optinally verified by PAM)
Destination number
```

I presume these are respectively the positional parameters supplied to the script, ie $1 to $3? If so, can a 4th parameter be added that supplies the script with the job ID number? This would mean I could reuse the same script with minor changes. The current parameters supplied would make for a much more complicated script to extract the email address of the client.

Best regards

Alex

**Comment by markuslindenberg** [comment]
Hi Alex, 

you're right, this will not work as expected, it will only work with Hylafax's `faxsend`, not with `gofaxsend`. 

But, your suggested change is easily doable and sounds sensible, i'll add the jobid as 4th parameter to the outgoing DynamicConfig script.
