### ISSUE TITLE
Fax send fails on real modems configured to Hylafax

### ISSUE THREAD

**Issue by michaaa** [gonicus/gofaxip#23]
This is somewhat like a feature request.

Well, gofaxip works great to connect a Hylafax server to a modern sip based PBX system. However, if the Hylafax server has a real modem configured besides freeswitch modems, sending out faxes throgh the other modem will fail, as long as the globally configured SendFaxCmd always pipes the fax send request to "gofaxsend". I tried configured SendFaxCmd per modem basis, but unfortunatley this won't work.

I'm thinking about writing a wrapper script which is used in SendFaxCmd, calling (original) faxsend or gofaxsend dependig on the addressed modem.

However, could it be possible to make this descision inside of gofaxsend? If modem line is something else than freeswitch[0-9], a (configurable) fallback SendFaxCmd is called, defaulting to faxsend...

**Comment by markuslindenberg** [comment]
Hi, 

I think a few lines of shell script wrapping/executing `gofaxsend` and `faxsend` would be the perfect solution for this. Technically we could put this into gofaxip, but I'd rather like to keep gofaxip as plain and simple as possible, especially when it's very easy to use a simple script instead. 

We currently don't have the requirement or aim to support complex or mixed environments with other technologies out of the box. The goal here is to provide rock solid standalone SIP connected Hylafax server. I have also declined to support setups that aim to integrate gofaxip into existing FreeSWITCH based PBXes for the same reasons.

If you would like to contribute a wrapper script I'd be happy to include it to be shipped in the `examples` folder.
