### ISSUE TITLE
Need to setup the gateway to be used with DynamicConfigOutgoing

### ISSUE THREAD

**Issue by rbetancor** [gonicus/gofaxip#26]
It's possible from the DynamicConfigOutgoing script to setup the gateway to be used in and outbound fax send?

For the pourpose of accounting, we need to send out faxes by diferent gateways definitions on freeswitch, we are able to setup the CallerID from the DynamicConfigOugoing script, but don't find a way to setup witch gw to use.

**Comment by markuslindenberg** [comment]
Hi, 

yes, that's possible since commit b2b1d12c976f251891f97db5a1227a9b58290027, but it is not included in the released Package yet so you have to manually build gofaxip or the package yourself.

You can set `Gateway: xyz` in the DynamicConfigOutgoing script.

**Comment by rbetancor** [comment]
Thanks you, but I have tryed to build myself, but the Debian build instrucstions doesn't work:

rabs@juno:~/gofaxip$ git-buildpackage
gbp:error: upstream/1.0 is not a valid treeish

[...]

rabs@juno:~/gofaxip$ dpkg-buildpackage
dpkg-buildpackage: source package gofaxip
dpkg-buildpackage: source version 1.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Markus Lindenberg <lindenberg@gonicus.de>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build gofaxip
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang --with=systemd
   dh_testdir -O--buildsystem=golang
   dh_auto_clean -O--buildsystem=golang
   dh_clean -O--buildsystem=golang
 dpkg-source -b gofaxip
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../gofaxip_1.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b gofaxip gave error exit status 255

**Comment by markuslindenberg** [comment]
Try doing a binary only build with `dpkg-buildpackage -b`

The command I use to build package is this:

```
dpkg-buildpackage -us -uc -rfakeroot -b -d
```

I need `-d` because I usually don't use a golang package from Debian's repository.

**Comment by rbetancor** [comment]
Also failed:

dh_auto_build -- -ldflags "-X main.version=1.0"
warning: "/..." matched no packages
can't load package: package .: no buildable Go source files in /home/rabs/gofaxip/obj-x86_64-linux-gnu
dh_auto_build: go install -v -ldflags -X main.version=1.0 returned exit code 1
debian/rules:8: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/rabs/gofaxip'
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

I was following the instructions to build on a Debian 8 system, so the only installed Go version is the one from the golang packages from the repositoriy.

**Comment by rbetancor** [comment]
I get to the point of building the binaries myself ... but the Gateway option seems not to work ...

On a test DynamicConfigOutgoing I have:

`#!/bin/bash

echo $@ >> /tmp/params
echo "FAXNumber: 19495555555"
echo "Gateway: customer1"
echo "LocalLine: +1 949 5555555"
echo "TagLine: Test FAX Machine"`

So it's supposed that if I do a sendfax, it should be done using sofia/gateway/customer1/19495555555 ... but instead, on the freeswitch log ... what I have is it trying to use sofia/fax/19495555555 ... and failing.

On the syslog it show:

Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: sendqfile.go:74: Calling DynamicConfig script etc/DynamicConfigOutgoing
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: sendqfile.go:121: Logging events for commid 00008225 to log/c00008225
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: sessionlog.go:69: Processing HylaFAX Job 9 as 1b9e5fd9-f2a3-4924-b672-0533d58273ff
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: sessionlog.go:69: Originating channel to 19495555555
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: sessionlog.go:69: Originate failed with hangup cause NORMAL_TEMPORARY_FAILURE
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: main.go:85: Error processing qfile sendq/q9: NORMAL_TEMPORARY_FAILURE
Jan 31 04:33:28 vm-test-faxserver gofaxsend[26675]: main.go:92: Exiting with status 0

Is there any way to trace this and let it works.

**Comment by rbetancor** [comment]
Finally got it working, after cleaning all and rebuilding the binaries again, seems I misscopied the created binary.

**Comment by michaaa** [comment]
@rbetancor What did you have changed to get rid of that

```
can't load package: package .: no buildable Go source files in /home/rabs/gofaxip/obj-x86_64-linux-gnu
dh_auto_build: go install -v -ldflags -X main.version=1.0 returned exit code 1
```
message?

I'm stuck at this point. Seems like it cannot find the go source tree in this dpkg-buildpackage environment. No difference if I use golang package from Debian repository or  a go binary tree...

**Comment by rbetancor** [comment]
Still unable to build the package ... but was able to build the binaries

What I did:

git clone https://github.com/gonicus/gofaxip
cd gofaxip
apt install dh-golang dh-systemd git-buildpackage
mkdir ~/go
export GOPATH=$HOME/go
cd gofaxsed && go build
cd gofaxd && go build

**Comment by denzs** [comment]
Sorry for the long delay...

I just uploaded a recent release, so there should be no need to build by yourself if you use amd64.

At the same time i updated the build instructions,
so if you still want/need to build by your own i hope that helps! :)

**Comment by michaaa** [comment]
Thanks for the new release version, but I don't know what's wrong at my site. I'm still not able to build packages as described. I get the following error:

```
mscloud :: ~ » git clone https://github.com/gonicus/gofaxip
Cloning into 'gofaxip'...
remote: Counting objects: 544, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 544 (delta 1), reused 0 (delta 0), pack-reused 537
Receiving objects: 100% (544/544), 202.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (264/264), done.
Checking connectivity... done.
mscloud :: ~ » cd gofaxip
mscloud :: ~/gofaxip ‹master› » dpkg-buildpackage -us -uc -rfakeroot -b
dpkg-buildpackage: source package gofaxip
dpkg-buildpackage: source version 1.1-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Sebastian Denz <denz@gonicus.de>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build gofaxip
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang --with=systemd
   dh_testdir -O--buildsystem=golang
   dh_auto_clean -O--buildsystem=golang
   dh_clean -O--buildsystem=golang
 debian/rules build
dh build --buildsystem=golang --with=golang --with=systemd
   dh_testdir -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/ms/gofaxip'
dh_auto_build -- -ldflags "-X main.version=1.1"
warning: "/..." matched no packages
can't load package: package .: no buildable Go source files in /home/ms/gofaxip/obj-x86_64-linux-gnu
dh_auto_build: go install -v -ldflags -X main.version=1.1 returned exit code 1
debian/rules:8: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/ms/gofaxip'
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
I guess there's something wrong with the created resouce directory obj-x86_64-linux-gnu while building.

**Comment by denzs** [comment]
Which version of dh-golang do you use?
I am using _dh-golang - 1.19ubuntu1_

And we are using the latest version of golang (not from the debian repos)
-> see https://github.com/niemeyer/godeb

When using golang from godeb instead of the debian version you may need to add the -d flag to dpkg-buildpackage...

I've just rebuild the release 1.1-1 with go 1.8 one minute ago on Ubuntu 14.04.5

**Comment by michaaa** [comment]
Well, I tried to build on a standard Debian 8 system:

```
golang-go                         2:1.3.3-1             amd64
dh-golang                         1.6                   all
```

then, the old dh-golang on Debian can be the reason for the problem.

**Comment by denzs** [comment]
Finally i was able to build the gofax package in Debian Jessie...
I did:
* use dh-golang from jessie-backports
* use go 1.8 via godeb (not sure if necessary)
* use _-d_ for _dpkg-buildpackage_
* make sure GOPATH is set

I hope that helps...

**Comment by michaaa** [comment]
Yeah, got it building a package for me...

I had to install both dh-golang **and** golang-go from jessie-backports

`sudo apt install dh-golang/jessie-backports golang-go/jessie-backports golang-src/jessie-backports`

as it still meets the configured depency, it's not nessesary to add _-d_ to _dpkg-buildpackage_

Of course, the Debian backport sources have to be configured in /etc/apt/sources.list, f.i. this way:

```
deb-src http://ftp.debian.org/debian/ jessie-updates main contrib non-free
deb http://ftp.debian.org/debian jessie-backports main contrib non-free
```
