### ISSUE TITLE
SIP Display Name

### ISSUE THREAD

**Issue by michaaa** [gonicus/gofaxip#27]
By default, the SIP Display Name (used in SIP From: attribute) is set to Hylafax username.

![bildschirmfoto_2017-02-01_um_12_26_10](https://cloud.githubusercontent.com/assets/134079/22505191/68969eb2-e87a-11e6-9424-36053db693a5.png)

Is it possible to disable the display-info attribute or defaulting it to the username value or something else? Maybe this is possible by manipulating freeswitch / mod_sofia parameters, but I did not found anything working in the documentation.

**Comment by denzs** [comment]
This can be overridden by setting the sender in the qfile, for example by using the sendfax parameter _-f_
`sendfax -f Foooo  -d 0123456 testfax.tif`

leads to:
```
...
From: "Foooo" <sip:820@1.2.3.4>;tag=ryeQeptNBSSFm
...
```

**Comment by michaaa** [comment]
This is correct so far, but usually users don't send faxes using the "sendfax" command on the command line. They use a Hylafax client, uploading their faxes to the server, and authenticating with their (activated) "fax-send"-account. Hylafax takes the username to fill out the SENDER attribute in an outgoung fax file (Or is there a way to change that behaviour in Hylafax?). However, this field is used by gofaxsend and finally freeswitch to set the real name part in the SIP From: attribute. 

However, I fixed it for myself by changing gofaxsend, using the outgoing fax number for real name instead of using the "SENDER" attribute for it. But this looks like some kind of "quick and dirty" fix for this.

To understand the reason for my request at all: This is because of some users don't want to "show" their user name to called station, as of some PBX use the real name field (from the "From:"-attribute) to show up in display as of the caller number instead. Other strange PBX don't like the real name field to be alphanumeric at all. ...weird things out there. :)

**Comment by denzs** [comment]
So having a configswitch for setting the outbound displayname to the calleridnum or nothing would solve your problem?

**Comment by denzs** [comment]
please have a look at 905f18ea5fd09a2b3300925b6343588b34a9f39d

**Comment by michaaa** [comment]
Great! That's it! 👍

**Comment by denzs** [comment]
:blush:
