### ISSUE TITLE
build error on raspberrypi

### ISSUE THREAD

**Issue by vasyugan** [gonicus/gofaxip#30]
Trying to build on a raspberrypi b+, with raspbian, Jessie:

jr@raspbian:~/src $ git clone https://github.com/gonicus/gofaxip
Klone nach 'gofaxip'...
remote: Counting objects: 544, done.
remote: Total 544 (delta 0), reused 0 (delta 0), pack-reused 544
Empfange Objekte: 100% (544/544), 199.72 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (267/267), Fertig.
Prüfe Konnektivität... Fertig.
jr@raspbian:~/src $ cd gofaxip
jr@raspbian:~/src/gofaxip $ dpkg-buildpackage -us -uc -rfakeroot -b
dpkg-buildpackage: Quellpaket gofaxip
dpkg-buildpackage: Quellversion 1.1-1
dpkg-buildpackage: Quelldistribution unstable
dpkg-buildpackage: Quellen geändert durch Sebastian Denz <denz@gonicus.de>
dpkg-buildpackage: Host-Architektur armhf
 dpkg-source --before-build gofaxip
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang --with=systemd
   dh_testdir -O--buildsystem=golang
   dh_auto_clean -O--buildsystem=golang
   dh_clean -O--buildsystem=golang
 debian/rules build
dh build --buildsystem=golang --with=golang --with=systemd
   dh_testdir -O--buildsystem=golang
   dh_update_autotools_config -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/jr/src/gofaxip'
dh_auto_build -- -ldflags "-X main.version=1.1"
warning: "/..." matched no packages
	go install -v -ldflags "-X main.version=1.1"
can't load package: package .: no buildable Go source files in /home/jr/src/gofaxip/obj-arm-linux-gnueabihf
dh_auto_build: go install -v -ldflags -X main.version=1.1 returned exit code 1
debian/rules:8: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/jr/src/gofaxip'
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2
jr@raspbian:~/src/gofaxip $

**Comment by denzs** [comment]
sorry for the late reply...
you have to install golang and dh-golang from jessie-backports for a successful build.

i just updated the build instructions
