### ISSUE TITLE
Dial rules

### ISSUE THREAD

**Issue by tompinzler** [gonicus/gofaxip#42]
It seems like I'm not able to use dial rules as described here:

http://www.hylafax.org/man/4.2.2/dialrules.4f.html

Does GoFax.IP ignore dial rules or am I doing something wrong?

**Comment by tompinzler** [comment]
To explain my motivation a bit more:

If enter a number into my Hylafax client with a white space (e.g. 0049 89338829 23) Freeswitch is responding with "INVALID_NUMBER_FORMAT". I was hoping to strip white spaces (and other unwanted characters) using dialrules. If there is another way to strip unwanted characters I'm happy to do it without dialrules.

**Comment by denzs** [comment]
After running over the documentation and sources very quick i would expect the hylafax server to be responsible for applying the dialrules?!

As your are posting a german phone number, maybe this helps you in locating the root of the problem:
https://lists.opensuse.org/archive/opensuse-isdn-de/2002-11/msg00008.html

If you find something useful, please add it to this issue :)

**Comment by sjaeckel** [comment]
@tompinzler can you please check with my latest version?
