### ISSUE TITLE
integration question for home usage

### ISSUE THREAD

**Issue by gedw99** [gonicus/gofaxip#43]
Can this work if I only have a dynamic WAN IP and no domain name mapped to your WAN.

Please correct me where i am probably wrong here:
1. WAN IP will change occasionally, and so need any other external devices to be told when it does ?
- so that callers calling in have the right IP.
2. For PSTN, i need to sign up somewhere to get a DID ( a real phone number termination), and then do some config ?
- The idea is so that people can call me from normal telephones, and i can call out.

**Comment by denzs** [comment]
This is not really a gofax.ip specifix question..

As your already mentioned, for PSTN connectivity you will need a sip account with a corresponding phone number from a provider. For "best fax experience" choose a provider with proper t.38 support!

To handle the dynamic ip adress you have to configure a small registration interval, but that should be discussed with your provider...

**Comment by gedw99** [comment]
Thanks for the tips. Its those little bits of info which really help me.
Ok will make sure its t.38 supported. Can you recommend a Provider by any
chance. So many out there.

Planning to use a blockchain for distributing the Ip address since its
global distributed.

**Comment by denzs** [comment]
see https://www.voip-info.org/wiki/view/VOIP+Service+Providers+T.38 for example

btw i am pretty sure there is no need to use blockchain... :flushed:
the problems is already solved -> you want to read about sip registrations

**Comment by gedw99** [comment]
thanks - did not know about SIP registrations.. ) again thanks for the tip.

Ok found a good explanation.
:
https://andrewjprokop.wordpress.com/2014/05/29/understanding-sip-registration/

SO this allows all knows to get the Ip address as it changes. This works
eve when your device is outside the home WAN ?

**Comment by denzs** [comment]
I dont get what you mean by "when your device is outside the home WAN" ?!

The registration mechanism ensures your provider knows your current ip adress so it is able to route incoming calls to your device...

**Comment by gedw99** [comment]
Soryr about delay.
Its because i have a non static IP. So i assuem there is a way to notify upstream when the Ip address at home changes maybe ?

**Comment by denzs** [comment]
As i already said, this is not a gofax.ip specific question... Please try to understand SIP Registrations (regarding the dynamic IP) and/or ask your provider about your situation...

**Comment by gedw99** [comment]
Sorry - i missed that and did not see this is already closed.
I will work it out with the DID provider.
