### ISSUE TITLE
Known good FreeSWITCH versions

### ISSUE THREAD

**Issue by sjaeckel** [gonicus/gofaxip#44]
Have you got a list of FreeSWITCH versions that you've tested and where you're sure they work properly regarding T.38?

TIA

**Comment by denzs** [comment]
Our production is still running 1.6.15 and is working fine!

As mentioned in https://github.com/gonicus/gofaxip/issues/31#issuecomment-349691419 FreeSWITCH 1.6.16 should be fine too.

In 1.6.17 the behaviour described in https://freeswitch.org/jira/browse/FS-10824 is introduced and leads to problems regarding the signaling in some setups.
