### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by micmicsuarez** [gonicus/gofaxip#46]
Hi guys,

I planned to create an automated tests for your app. I'm not sure if it is easy or not. Any advice? 

Thanks,
Michael

**Comment by corny** [comment]
I suggest you to use docker and Circle CI.

**Comment by micmicsuarez** [comment]
Great! Thanks @corny. :)

**Comment by corny** [comment]
I did some first steps in #47

**Comment by micmicsuarez** [comment]
Thanks @corny. :)

**Comment by denzs** [comment]
#47 is merged, thx @corny  :)

**Comment by denzs** [comment]
I'll close this issue, as there was no more activity...
