### ISSUE TITLE
Feature request: Support Asterisk

### ISSUE THREAD

**Issue by vasyugan** [gonicus/gofaxip#48]
It seems, Freeswitch is lagging behind quite a bit. It does not support Debian 9, which includes current Raspbian. Plus, it is not part of Debian, and for non x86 platforms needs to be built from source.
Would it be possible to instead use Asterisk, which seems to be much better integrated with Debian, it is available directly from the repos for any Debian and Ubuntu version.

**Comment by denzs** [comment]
You're propably right... the way FreeSWITCH is handling releases and supporting plattforms is propably not the best one could think of...

But supporting Asterisk would be more of a rewrite from scratch than just adding a feature ;)

Maybe we'll take this into consideration in the future, but for the moment we do not have concrete plans to implement this...
