### ISSUE TITLE
gofaxip and IAXmodem mixed usage

### ISSUE THREAD

**Issue by dachosd** [gonicus/gofaxip#5]
Hello,

I have a question regarding gofaxip and IAXmodem mixed usage. 

What I am trying to achieve is to send some fax'es via gofaxsend and some via IAXmodems.

 Is it possible for gofaxip to use IAXmodems' configs?

Best regards,
Dragan Saraginov

**Comment by markuslindenberg** [comment]
We currently have no plans to actively add support for mixed usage with other FAX modem stacks or a FreeSWITCH that is also used for other (PBX) functionality. 

If you or someone else can confirm that this setup will work I'd be happy to add it to the documentation, It's just not a use case we have in mind.
