### ISSUE TITLE
DynamicConfigOutgoing and external 

### ISSUE THREAD

**Issue by telvenes** [gonicus/gofaxip#52]
Inside DynamicConfigOutgoing i am calling a external script like this:
/usr/bin/php /script/dcu.php

I have set up postfix fax2mail with and postfix to block unautorised senders with spf and so on.
So inside this php script i like to connect to the database and se if the sender is autorised to send and if he is i can echo "RejectCall: false"; and if he is not i want to echo "RejectCall: false";

i databasen har jeg feks en tabell som innholder user@domain.tld or *@domain2.tld wich means user@domain.tld can send fax to mail. and all users of domain2.tld can also use fax to mail.

Anyone done something like this? is this the correct method todo this or should i make a script that postfix calls to check before running the /usb/bin/faxmail command?

appreciate all the help

**Comment by telvenes** [comment]
sry i forgot to day that what i am looking for is what is the parameter for the sender email inside DynamicConfigOuthoing

**Comment by denzs** [comment]
I am not sure, if i understand correctly...

It depends on how you pass over the faxjob from postfix to hylafax, i would expect the second parameter:
* Owner (User ID as set sendfax -o or the FAXUSER environment variable, optinally verified by PAM)

to contain the information about the sending user.

But as i said, that totally depends on how you pass the faxjob from postfix to hylafax..

If you want your unauthorized users to get feedback it would propably be easier to handle this inside of postfix..
