### ISSUE TITLE
Full freeswitch PBX required? 

### ISSUE THREAD

**Issue by k4tfish** [gonicus/gofaxip#55]
It's not clear to me if we need the full stack or just an working SIP account to make hylafax easy VoIPable.

**Comment by cron2** [comment]
The way this works: you need the full freeswitch stack, as the actual faxing is done by mod_spandsp.

If you have an asterisk server to talk to, you can use "hylafax + iaxmodem", but that's a different project (and it only speaks IAX, not SIP).

**Comment by denzs** [comment]
@k4tfish What do you mean with "full stack"?
There is no need to have a FreeSWITCH based PBX, you only have to
* install the packages mentioned in the Readme
* copy the provided (non pbx) FreeSWITCH configs
* add your SIP account to the config
Thats it :)

**Comment by k4tfish** [comment]
Thanks for the clarification @denzs 
Full stack was misleading, I meant a fully working fs PBX. 

Going to give Gofax.IP a try :)
