### ISSUE TITLE
Install instructions could use some improvement

### ISSUE THREAD

**Issue by helloadmin** [gonicus/gofaxip#6]
Let me start by saying thank you for authoring this project and posting it.  The amount of time, effort and will to prioritize open source coding over other personal priorities is commendable and I really appreciate your effort.  

I'm more of a freeswitch guy who is/was trying to maintain a faxserver on Asterisk and really looking forward to just using freeswitch.  I'm not a complete newbie but had some trouble with the initial parts of the instructions.  Starting with a clean Debian install, here are some of the things I had to do:

Please correct / update if there is a better way or its not the correct way....

> sudo apt-get install git
> sudo apt-get install build-essential
> wget https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz
> tar -C /usr/local -xzf go1.4.linux-amd64.tar.gz
> export PATH=$PATH:/usr/local/go/bin

> mkdir ~/gofaxip
> cd ~/gofaxip
> git init
> git clone https://github.com/gonicus/gofaxip.git
> export GOPATH=$(pwd)
> go install gofaxd gofaxsend
> sudo cp bin/* /usr/local/sbin/

**Comment by markuslindenberg** [comment]
Yes, that's exactly how to install Go. :)

I think you don't need `build-essential`, only `make` if you want to use the `Makefile`, which is recommended. 

Maybe a link to http://golang.org/doc/install#tarball for installing go is a better solution? I don't really want to track go versions in the README. Anyway, it's a good idea to include the exact commands to build gofax.ip.

**Comment by helloadmin** [comment]
Markus,  I need to get a fax blast server up.  Are you interested in a couple consulting hours to install gofaxip and Hylafax on an existing FreeSWITCH / FusionPBX install?
