### ISSUE TITLE
gofaxip cannot send faxes to itself

### ISSUE THREAD

**Issue by andbag** [gonicus/gofaxip#61]
We would like to replace our analogue faxes with gofaxip and hylafax :). There will be scenarios where users send a fax with hylafax that hylafax itself has to receive again. However, the PBX (fusionPBX/freeswitch) says that the channel is BUSY. The fax server (hylafax/gofaxip/freeswitch) is registered as an extension on the PBX. Do I have to look for the solution on the hylafax side or on the PBX side?

Thanks in advance & kind regards

**Comment by denzs** [comment]
Hi Andreas,
this sounds like a limitation on side of the pbx..
As you said the Faxserver is registered via SIP, maybe it is created like a regular user with one line.
I would try to integrate the Faxserver via static a SIP-Trunk to the PBX :)

**Comment by andbag** [comment]
Hi Sebastian,

yes, you are right. After studying for a while, I realised that I also need to set up a gateway and a correct dialplan for the return channel in the PBX to the fax server. The solution is to bridge an inbound channel via SIP-Registratin (a-leg) and an outbound channel via gateway (b-leg) back to the fax server itself. It works now :).

Thank you for the quick reply.
