### ISSUE TITLE
Debian Bookworm Support and freeswitch compability with version 10.10.10

### ISSUE THREAD

**Issue by haup** [gonicus/gofaxip#70]
Hi, 

the last release of gofaxip is almost 3 years ago and I wonder if the documentation is still valid to use debian buster, even though its not even oldstable anymore? 

Highly appreciated your work and some feedback :)

**Comment by luebke-dev** [comment]
Hey,
It also works on debian 10 and 11. Bookworm is untested currently but im pretty sure that it also works there.
