### ISSUE TITLE
instruction for using multiple gateways

### ISSUE THREAD

**Issue by neerajnagi** [gonicus/gofaxip#8]
How can gofaxip use multiple gateways and exactly how will calls will be distributed among those gateways. Kindly provide instructions for them.

**Comment by markuslindenberg** [comment]
Hi, 

I'm sorry for the delay, the Github notification somehow got lost and I was busy with other stuff so I didn't take a look at the issue tracker. 

Right now multiple gatways are supported as a failover mechanism, if the first configured gateway isn't available, the next configured gateway will be used. 

To use more than one gateway:
* Define more than one gateway in `/etc/freeswitch/gateways/` (using different names)
* Add multiple `gateway=` options to the config file's `[freeswitch]` section.

The Gateways are tried in configured order until a working gateway is found by using freeswitch's `|` operator as documented in https://freeswitch.org/confluence/display/FREESWITCH/bridge#bridge-ImplementingFailover
